export const CMC_LISTINGS_URL = 'https://api.coinmarketcap.com/v2/listings/'
export const CMC_LOGO_URL = 'https://s2.coinmarketcap.com/static/img/coins/32x32/'
export const BINANCE_TICKERS_24H_URL = 'http://localhost:8080/crypto/api/tickers'
export const CORS_PROXY_URL = 'https://cors-anywhere.herokuapp.com/'
export const KRAUG_CRYPTO_API = 'http://localhost:8080/crypto/api/'
export const CURRENT_RSI = 'rsi/now'
export const PRISFORSKJELL = 'http://localhost:8080/crypto/api/tickers/compare?min=5&max=50'
